spring.application.name=HuyenTrang

spring.datasource.url=jdbc:mysql://db:3308/demo
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=80